---
apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketAccessClass
metadata:
  name: fb-access-rw
driverName: flashblade.cosi.purestorage.com
authenticationType: KEY
parameters:
  accessMode: readwrite
---
apiVersion: objectstorage.k8s.io/v1alpha1
kind: BucketAccessClass
metadata:
  name: fb-access-ro
driverName: flashblade.cosi.purestorage.com
authenticationType: KEY
parameters:
  accessMode: readonly
