apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pure-cosi-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: pure-cosi-config
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: cluster/{{ cluster_name }}/pure-cosi
