apiVersion: v1
kind: Secret
metadata:
  name: pure-cosi-config
  namespace: pure-cosi-system
type: Opaque
stringData:
  PUREFB_TARGET: "10.3.11.50"
  PUREFB_REALM: "naved-int-test"
  PUREFB_S3_ACCOUNT: "deleteme"
  S3_ENDPOINT: "10.8.0.9"
  PUREFB_API_TOKEN: "scoped-token"
