apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cosi-bucket-viewer
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - objectstorage.k8s.io
  resources:
  - bucketclaims
  - bucketaccesses
  - bucketclasses
  - bucketaccessclasses
  verbs:
  - get
  - list
  - watch
