apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/serviceaccount.yaml
  - resources/driver-rbacs/clusterrole.yaml
  - resources/driver-rbacs/clusterrolebinding.yaml
  - resources/user-rbacs/editcr.yaml
  - resources/user-rbacs/viewcr.yaml
  - resources/externalsecret.yaml
  - resources/deployment.yaml
  - resources/bucketclass.yaml
  - resources/bucketaccessclass.yaml
